Vagrant.configure(2) do |config| 
  config.vm.define "gitlab" do |conf| 
    conf.vm.box = "centos/7" 
    conf.vm.hostname = 'gitlab.example.com' 
    conf.vm.network "forwarded_port", guest: 80, host: 8080
    conf.vm.network "forwarded_port", guest: 443, host: 8443
    conf.vm.provider "virtualbox" do |v| 
      v.memory = 2048 
      v.cpus = 2 
    end
  end